refactor: benefits section
Code-craft-studios/vigui pull request #29
Opened 2023-07-25 23:53 UTC by patrickwebsdev

2023-07-26 13:12 UTC, Shadowrunner11 requested changes

2023-07-26 13:12 UTC, Shadowrunner11 commented on src/styles/colors.css
> +    /*--bg: #1c1c1c;  TEMPORARY COMMENT*/
borrar

2023-07-26 13:12 UTC, Shadowrunner11 commented on src/ui/IconText/styles.module.css
> +  width: 100%;
El problema de forzar q la imagen ocupe todosu contenedor es q se pierde la proprocionde la imagen por eso solo escojemos una de las medidas, en estecaso creo q la mas importante visualmente sera el height, sin embargo veo q limitas el tamaño de la altura(explicar, si esposible diagramar wireframe antes y despues).

Otro punto importante es q ahora se prefiere usar las propiedades logicas, el correspondiente a height es `inline-size`, por ejemplo

2023-07-26 13:12 UTC, Shadowrunner11 commented on src/ui/IconText/styles.module.css
>    max-width: 25ch;
El equivalente logico de `max-width` es `max-inline-size`

2023-07-26 13:12 UTC, Shadowrunner11 commented on src/components/Benefits/index.tsx
> +]
Siento que esta data debe venir por props y estos valores el default o mejor aun q next js los cargue estaticamente 

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

Sin embargo esto ya es otra responsabilidad, entonces seria bueno pensar en este componente con que soportara la data y pasarselo por props o b, acamismo resolver el problema del data fetching, xq receurda q deseamos q esta daatavenga de un cms y tengamos deploys incrementales

2023-07-27 04:13 UTC, patrickwebsdev commented on src/ui/IconText/styles.module.css
> +  width: 100%;
Ahora se utiliza max-block-size y inline-size.

Demostración de porque se limita el tamaño de la altura:

(Antes)
![Imagen de WhatsApp 2023-07-27 a las 01 09 47](https://github.com/Code-craft-studios/vigui/assets/71416731/ba4827ac-df35-4ab0-a5fe-3941c8c56fef)

(Despues)
![Imagen de WhatsApp 2023-07-27 a las 01 10 05](https://github.com/Code-craft-studios/vigui/assets/71416731/8ec2beb9-f490-4c2e-8453-96f25cb0bb1d)

Sin importar el tamaño del icono, siempre serán simétricos.

2023-07-27 04:46 UTC, Shadowrunner11 requested changes

2023-07-27 04:46 UTC, Shadowrunner11 commented on src/components/Benefits/index.tsx
> +  const benefitsToUse = customBenefits ?? defaultBenefits;
Este const de la 44 se recalcula nuevamente, en el destrcuturing se puede hacer la asignacion

```tsx
const Benefits = ({ customBenefits =  defaultBenefits}) => 
```

```

2023-07-27 04:48 UTC, Shadowrunner11 approved these changes

2023-07-27 04:48 UTC, merged