refactor: remove box's from Benefits and OtherServices | minor css ch…
Code-craft-studios/vigui pull request #34
Opened 2023-07-29 05:16 UTC by patrickwebsdev

…anges | suppresed hydratation warnings

2023-07-29 06:25 UTC, Shadowrunner11 requested changes

2023-07-29 06:25 UTC, Shadowrunner11 commented on public/images/bg-gradient-right.svg
Xq no crear este gradiente conc css en lugar q sea un svg?

2023-07-29 06:25 UTC, Shadowrunner11 commented on src/app/layout.tsx
> +    <html lang='es' suppressHydrationWarning={true}>
Quitar el true

2023-07-29 06:25 UTC, Shadowrunner11 commented on src/components/Benefits/styles.module.css
> +}
la responsabilddad del container es los breakpoints no el layout presentation, intentar usar patron Box adentro del container

2023-07-29 06:25 UTC, Shadowrunner11 commented on src/components/OthersServices/styles.module.css
> +}
Ver comentario anterioor

Ademas si se esta repitiendo los estilos hay la posiblidad q se peuda abstraer un en layout y solo pasar las clases

Como ya van varios componentes q estan propdirlleando clases construir un HOC withClassName o un HOF (mas moderno es el HOF)

2023-07-29 06:25 UTC, Shadowrunner11 commented on src/ui/Title/index.tsx
> +    <Typography className={`${styles.title} ${variants[variant]}`} fontWeight={700} textAlign={'center'}>
Si se esta repitiendo codigo hay una posiblidad de abstracion aunque CVA ya lo hace por uno, o creas tu HOC mas utils de esto o usas cva

2023-07-29 06:25 UTC, Shadowrunner11 commented on src/ui/Title/styles.module.css
>  }
Tratar de llevar una metodologia, por ejemplo primaryTheme seria en el caso de OCSSpara dejar claro al q usara esto sin q vea tu css por si hay a futuro una abstracion del layout

2023-07-29 14:24 UTC, patrickwebsdev commented on public/images/bg-gradient-right.svg
Esta mas optimizado el SVG

2023-07-30 01:21 UTC, Shadowrunner11 commented on public/images/bg-gradient-right.svg
#36

2023-07-30 02:21 UTC, Shadowrunner11 commented on src/components/Benefits/styles.module.css
> +}
Se borro

2023-07-30 02:21 UTC, Shadowrunner11 commented on src/components/OthersServices/styles.module.css
> +}
Se borro

2023-07-30 02:59 UTC, Shadowrunner11 approved these changes

2023-07-30 03:00 UTC, merged